openapi: 3.0.3
info:
  title: "\u9879\u76EE API"
  version: 1.0.0
  description: "\u7528\u4E8E\u7BA1\u7406\u9879\u76EE\u7684 API"
paths:
  /api/items:
    get:
      summary: "\u83B7\u53D6\u6240\u6709\u9879\u76EE"
      description: "\u83B7\u53D6\u9879\u76EE\u5217\u8868\uFF0C\u652F\u6301\u5206\u9875\
        \u548C\u6392\u5E8F"
      tags:
      - "\u9879\u76EE"
      operationId: getItems
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 10
          description: "\u8FD4\u56DE\u7ED3\u679C\u7684\u6700\u5927\u6570\u91CF"
          title: Limit
        description: "\u8FD4\u56DE\u7ED3\u679C\u7684\u6700\u5927\u6570\u91CF"
      - name: offset
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          default: 0
          description: "\u7ED3\u679C\u7684\u504F\u79FB\u91CF"
          title: Offset
        description: "\u7ED3\u679C\u7684\u504F\u79FB\u91CF"
      - name: sort_by
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: name
          description: "\u6392\u5E8F\u5B57\u6BB5"
          title: Sort By
        description: "\u6392\u5E8F\u5B57\u6BB5"
      - name: order
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          default: asc
          description: "\u6392\u5E8F\u987A\u5E8F (asc \u6216 desc)"
          title: Order
        description: "\u6392\u5E8F\u987A\u5E8F (asc \u6216 desc)"
    post:
      summary: "\u521B\u5EFA\u65B0\u9879\u76EE"
      description: "\u521B\u5EFA\u4E00\u4E2A\u65B0\u7684\u9879\u76EE"
      tags:
      - "\u9879\u76EE"
      operationId: createItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        required: true
  /api/items/{x_request_path_item_id}:
    get:
      summary: "\u83B7\u53D6\u5355\u4E2A\u9879\u76EE"
      description: "\u901A\u8FC7ID\u83B7\u53D6\u9879\u76EE"
      tags:
      - "\u9879\u76EE"
      operationId: getItem
      parameters:
      - &id001
        name: id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: "\u66F4\u65B0\u9879\u76EE"
      description: "\u66F4\u65B0\u73B0\u6709\u9879\u76EE"
      tags:
      - "\u9879\u76EE"
      operationId: updateItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
        required: true
      parameters:
      - *id001
    delete:
      summary: "\u5220\u9664\u9879\u76EE"
      description: "\u5220\u9664\u73B0\u6709\u9879\u76EE"
      tags:
      - "\u9879\u76EE"
      operationId: deleteItem
      parameters:
      - *id001
components:
  schemas: {}
  securitySchemes: {}
tags: []
